on:
  push:
    branches:
      - master
  pull_request:

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci || true --json --output semgrep.json
        env:
           SEMGREP_RULES: p/default
        continue-on-error: true
      - run: ls -la
  
